### ISSUE TITLE
botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [JuaniLavenia/proyecto-web-final#20]
## Proceso

1. Ingrese a la pagina.
2. Baje hasta el final.

## Resultado esperado

Que los botones del footer tengan una funcion.

## Resultado actual

Lo botones no cumplen ninguna accion.

## Posible solución
 
Agregar una funcion a los botones o que los botones redireccionen a una page 404.

## Captura

![image](https://github.com/JuaniLavenia/proyecto-web-final/assets/53904695/a16f930b-1e87-450e-a215-bab023ce9ce7)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by JuaniLavenia** [comment]
Listo! Añadi una pagina de error 404 para los links/botones que no tienen funcionalidad o que no existan.
