### ISSUE TITLE
Texto fuera de lugar

### ISSUE THREAD

**Issue by Nidev-lab** [JuaniLavenia/proyecto-web-final#21]
## Proceso

Ingrese a la pagina.

## Resultado esperado

Que el texto este en su lugar.

## Resultado actual

El texto esta fuera de lugar.

## Captura

![image](https://github.com/JuaniLavenia/proyecto-web-final/assets/53904695/f67677be-edaf-4191-89cf-450ce86f80f3)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by JuaniLavenia** [comment]
Listo! Corregi para que todo el contenedor se ajuste debidamente a su contenido.

**Comment by Nidev-lab** [comment]
Perfecto con eso ya estariamos.
